on:
  push:
    tags:
      - "v*.*"

name: Deploy assets

jobs:
  build-and-deploy:
    name: Deploy assets
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@master

      - name: Set git env
        run: |
          echo "TAG_NAME=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: 22.12.0
      
      - name: Generate files.json
        run: node src/make.js $TAG_NAME

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Deploy public folder and assets
        run: |
          aws s3 sync ./src/public/ s3://${{ vars.S3_BUCKET }} --delete
          aws s3 sync ./src/files/ s3://${{ vars.S3_BUCKET }}
