on:
  push:
    tags:
      - 'v*.*.*'

name: Deploy assets

jobs:
  build-and-deploy:
    name: Deploy assets
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@master

      - name: Set git env
        run: |
          echo "TAG_NAME=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build make file
        run: pnpm build

      - name: Generate files.json
        run: pnpm make
        env:
          TAG_NAME: ${{ env.TAG_NAME }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Deploy public and files folders to S3
        run: |
          aws s3 sync ./src/files/ s3://${{ vars.S3_BUCKET }} --delete  --exact-timestamps &
          aws s3 sync ./src/public/ s3://${{ vars.S3_BUCKET }} --exact-timestamps &
          wait
